#include "mylib_api.h"        // const char* version(void);  (static-link API)
#include "mylib_plugin_abi.h" // mylib_plugin_api, MYLIB_PLUGIN_* (plugin ABI)
#include "mylib_export.h"     // MYLIB_EXPORT  (generated by add_mylib_plugin)

#include <cstdio>

namespace {

// ---------------------------------------------------------------------
// Internal helpers. Neither is declared in a public header, neither is
// marked MYLIB_EXPORT, and both live in an anonymous namespace, so:
//
//   * they have internal linkage (no external symbol in the object file);
//   * the plugin (MODULE) target is built with hidden visibility, so even
//     an external-linkage symbol would not reach the plugin's dynamic
//     symbol table on GCC/Clang/MinGW;
//   * MSVC exports nothing from a DLL that isn't __declspec(dllexport).
//
// Net effect: the only symbol a host can resolve from the plugin is the
// entry point mylib_plugin_get_api below. `version` itself is not exported
// by the plugin - a host reaches it only indirectly, through the api table.
// ---------------------------------------------------------------------

int add_numbers(int a, int b)
{
    return a + b;
}

double square_value(double x)
{
    return x * x;
}

} // namespace

// ---------------------------------------------------------------------
// The actual capability. Plain extern "C" linkage, NOT MYLIB_EXPORT: for
// the static library this is a normal linkable symbol; for the plugin it
// stays hidden and is only reachable via the api table.
// ---------------------------------------------------------------------
extern "C" const char* version(void)
{
    static char buffer[256] = {0};

    if (buffer[0] == '\0')
    {
        // Built once, on first call. The two internal helpers are exercised
        // here just to show they're real, callable code inside the library -
        // they're simply never reachable from outside it.
        const int sum = add_numbers(1, 2025);
        const double sq = square_value(2.0);

        std::snprintf(buffer, sizeof(buffer),
                      "mylib version 1.0.0 (internal check values: %d, %.1f)",
                      sum, sq);
    }

    return buffer;
}

// ---------------------------------------------------------------------
// Plugin entry point. This is the one and only symbol the plugin exports
// (MYLIB_EXPORT + hidden visibility everywhere else). A host resolves it by
// the name MYLIB_PLUGIN_ENTRY_NAME and calls it to get the api table.
// ---------------------------------------------------------------------
namespace {

const mylib_plugin_api g_plugin_api = {
    sizeof(mylib_plugin_api),   // struct_size
    MYLIB_PLUGIN_ABI_VERSION,   // abi_version
    &version                    // version
};

} // namespace

extern "C" MYLIB_EXPORT const mylib_plugin_api* mylib_plugin_get_api(void)
{
    return &g_plugin_api;
}
