#pragma once

// mylib_export.h is generated by CMake's GenerateExportHeader module (see
// src/CMakeLists.txt). It supplies the MYLIB_EXPORT macro, which expands to
// the right thing automatically for every target/compiler combination this
// project supports:
//
//   * GCC/Clang, building the shared library  -> __attribute__((visibility("default")))
//   * GCC/Clang, everything else               -> nothing (hidden by default)
//   * MSVC,      building the shared library  -> __declspec(dllexport)
//   * MSVC,      consuming the shared library -> __declspec(dllimport)
//   * any compiler, static library builds      -> nothing (MYLIB_STATIC_DEFINE)
#include "mylib_export.h"

#ifdef __cplusplus
extern "C" {
#endif

// Returns a pointer to a static, null-terminated ASCII string (at most 255
// printable characters plus the terminating '\0', i.e. it fits in a
// char[256]) describing the library's version. The pointer refers to
// storage owned by the library, is valid for the lifetime of the process
// (or, for the shared library, until it is unloaded), and must never be
// freed by the caller.
MYLIB_EXPORT const char* version(void);

#ifdef __cplusplus
} // extern "C"
#endif

// Function-pointer type matching version() above. Consumers that load this
// library dynamically at runtime (dlopen()/dlsym() on Linux, LoadLibrary()/
// GetProcAddress() on Windows) rather than linking against it directly only
// need to agree on this signature - they don't need mylib_export.h at all.
// It's provided here purely for convenience/documentation; test_sharedLib.cpp
// intentionally redeclares it locally to show that it's a self-contained
// requirement, not a build-time dependency on this header.
typedef const char* (*version_func_t)(void);
